### ISSUE TITLE
NTOS error for organic material printer and more

### ISSUE THREAD

**Issue by annikaRU** [NovaSector/NovaSector#2750]
Reporting client version: 515.1637

## Issue Summary

NTOS errors for most modular organic printers

## Round ID:
[10933](https://scrubby.melonmesa.com/round/10933)

Another modular broken item, NTOS errors for majority of the fabricators and organic material printers

## Testmerges:
- [[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou](https://github.com/NovaSector/NovaSector/pull/183)
- [Ooey Gooey Slimegirl Buffs Vol. 1](https://github.com/NovaSector/NovaSector/pull/1661)
- [[SEMI-MODULAR] Taur rework Pt. 2: Quadruped taurs (Part one)](https://github.com/NovaSector/NovaSector/pull/1976)
- [[MODULAR] Adds a new deathmatch modifier: Loadout enabled](https://github.com/NovaSector/NovaSector/pull/2665)

## Reproduction:

Error: Minified React error #300; visit https://reactjs.org/docs/error-decoder.html?invariant=300 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
   at rl (http://127.0.0.1:58761/asset.70262d9acd59e5ecfe7d1c8d847b60c0.js:9:65855)
   at dl (http://127.0.0.1:58761/asset.70262d9acd59e5ecfe7d1c8d847b60c0.js:9:77343)
   at ju (http://127.0.0.1:58761/asset.70262d9acd59e5ecfe7d1c8d847b60c0.js:9:119859)
   at vu (http://127.0.0.1:58761/asset.70262d9acd59e5ecfe7d1c8d847b60c0.js:9:114778)
   at rd (http://127.0.0.1:58761/asset.70262d9acd59e5ecfe7d1c8d847b60c0.js:9:114712)
   at gs (http://127.0.0.1:58761/asset.70262d9acd59e5ecfe7d1c8d847b60c0.js:9:114565)
   at Pl (http://127.0.0.1:58761/asset.70262d9acd59e5ecfe7d1c8d847b60c0.js:9:110777)
   at hu (http://127.0.0.1:58761/asset.70262d9acd59e5ecfe7d1c8d847b60c0.js:9:111650)
   at po (http://127.0.0.1:58761/asset.70262d9acd59e5ecfe7d1c8d847b60c0.js:9:48525)
   at Anonymous function (http://127.0.0.1:58761/asset.70262d9acd59e5ecfe7d1c8d847b60c0.js:9:109169)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E)
State: {"ckey":"latinfishy","interface":"Biogenerator","window":{"key":"[0x202904d]-main","size":null,"fancy":1,"locked":1}}

I am uncertain, but is safe to assume majority are broken 

![image](https://github.com/NovaSector/NovaSector/assets/147753662/3f648087-b5cf-4067-9154-7bff07a85990)

**Comment by FlufflesTheDog** [comment]
Fixed by https://github.com/NovaSector/NovaSector/pull/2793
