### ISSUE TITLE
Crafting NTOS error

### ISSUE THREAD

**Issue by annikaRU** [NovaSector/NovaSector#2973]
Reporting client version: 515.1639

## Issue Summary

Crafting menu brings a NTOS error

## Round ID:
[11015](https://scrubby.melonmesa.com/round/11015)

## Testmerges:
- [[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou](https://github.com/NovaSector/NovaSector/pull/183)
- [Ooey Gooey Slimegirl Buffs Vol. 1](https://github.com/NovaSector/NovaSector/pull/1661)
- [[SEMI-MODULAR] Taur rework Pt. 2: Quadruped taurs (Part one)](https://github.com/NovaSector/NovaSector/pull/1976)
- [Flashbangs now inform user if the security level is green, and during green alerts they must be ctrl+clicked to arm](https://github.com/NovaSector/NovaSector/pull/2553)
- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [Blueshield QOL with other code cleanup](https://github.com/NovaSector/NovaSector/pull/2816)
- [[SEMI-MODULAR] Telecomms Specialist](https://github.com/NovaSector/NovaSector/pull/2757)
- [Pipe Dreams: Disposals is actually usable as an escape again](https://github.com/NovaSector/NovaSector/pull/2852)

## Reproduction:

Open the crafting menu

TypeError: Can't call method on undefined
   at B.exports (http://127.0.0.1:57306/asset.4d3fedf578b97767f679d3b9e4955b1c.js:406:124644)
   at B.exports (http://127.0.0.1:57306/asset.4d3fedf578b97767f679d3b9e4955b1c.js:406:131687)
   at keys (http://127.0.0.1:57306/asset.4d3fedf578b97767f679d3b9e4955b1c.js:406:171281)
   at Anonymous function (http://127.0.0.1:57306/asset.4d3fedf578b97767f679d3b9e4955b1c.js:310:46108)
   at Anonymous function (http://127.0.0.1:57306/asset.4d3fedf578b97767f679d3b9e4955b1c.js:37:1724)
   at Anonymous function (http://127.0.0.1:57306/asset.4d3fedf578b97767f679d3b9e4955b1c.js:406:78965)
   at map (http://127.0.0.1:57306/asset.4d3fedf578b97767f679d3b9e4955b1c.js:406:146677)
   at C (http://127.0.0.1:57306/asset.4d3fedf578b97767f679d3b9e4955b1c.js:37:1689)
   at v (http://127.0.0.1:57306/asset.4d3fedf578b97767f679d3b9e4955b1c.js:37:1889)
   at h (http://127.0.0.1:57306/asset.4d3fedf578b97767f679d3b9e4955b1c.js:310:46080)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E)
State: {"ckey":"N/A","interface":"PersonalCrafting","window":{"key":"[0x21099ddc]-main","size":null,"fancy":1,"locked":1}}

**Comment by annikaRU** [comment]
Closed as it's upstream
