### ISSUE TITLE
Crafting Menu NTOS error

### ISSUE THREAD

**Issue by OzzyMcPseudonym** [NovaSector/NovaSector#2979]
## Issue Summary
Upon opening the crafting menu, I got an NTOS error. 

## Round ID:
11018

## Reproduction:
Open the Crafting Menu
Get an NTOS Error Like as follows:
TypeError: Can't call method on undefined
   at B.exports (http://127.0.0.1:59512/asset.4d3fedf578b97767f679d3b9e4955b1c.js:406:124644)
   at B.exports (http://127.0.0.1:59512/asset.4d3fedf578b97767f679d3b9e4955b1c.js:406:131687)
   at keys (http://127.0.0.1:59512/asset.4d3fedf578b97767f679d3b9e4955b1c.js:406:171281)
   at Anonymous function (http://127.0.0.1:59512/asset.4d3fedf578b97767f679d3b9e4955b1c.js:310:46108)
   at Anonymous function (http://127.0.0.1:59512/asset.4d3fedf578b97767f679d3b9e4955b1c.js:37:1724)
   at Anonymous function (http://127.0.0.1:59512/asset.4d3fedf578b97767f679d3b9e4955b1c.js:406:78965)
   at map (http://127.0.0.1:59512/asset.4d3fedf578b97767f679d3b9e4955b1c.js:406:146677)
   at C (http://127.0.0.1:59512/asset.4d3fedf578b97767f679d3b9e4955b1c.js:37:1689)
   at v (http://127.0.0.1:59512/asset.4d3fedf578b97767f679d3b9e4955b1c.js:37:1889)
   at h (http://127.0.0.1:59512/asset.4d3fedf578b97767f679d3b9e4955b1c.js:310:46080)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0; Zoom 3.6.0)
State: {"ckey":"justanormalhooman","interface":"PersonalCrafting","window":{"key":"[0x21096562]-main","size":null,"fancy":1,"locked":0}}

Also, clearing the BYOND cache doesn't fix this at all.
Supposedly this doesn't happen on TG, so I'm reporting it here.

**Comment by OzzyMcPseudonym** [comment]
Clicking "Show Server Revision" gives the following information:

Round ID: 11018
BYOND Version: 515.1637
Server revision compiled on: 2024-06-11T16:05:54+00:00
Master commit: [ea75750452830980e97434c7160b237594a2a448](https://github.com/NovaSector/NovaSector/commit/ea75750452830980e97434c7160b237594a2a448)
The following pull requests are currently test merged:
[#183: '[PORT] [SEMI-MODULAR] [JANK] Ports the lovely Character Directory which was ported from Coyote Bayou' by W4rd3nn at commit 20f64af154](https://github.com/NovaSector/NovaSector/pull/183)
[#1661: 'Ooey Gooey Slimegirl Buffs Vol. 1' by Nerev4r at commit 7902df0187](https://github.com/NovaSector/NovaSector/pull/1661)
[#1976: '[SEMI-MODULAR] Taur rework Pt. 2: Quadruped taurs (Part one)' by nikothedude at commit fc7d212c53](https://github.com/NovaSector/NovaSector/pull/1976)
[#2553: 'Flashbangs now inform user if the security level is green, and during green alerts they must be ctrl+clicked to arm' by vinylspiders at commit 1cfc2c2625](https://github.com/NovaSector/NovaSector/pull/2553)
[#2754: '[TESTING ONLY] Debugging overlay cap being reached with taur parts' by vinylspiders at commit c6104e5204](https://github.com/NovaSector/NovaSector/pull/2754)
[#2816: 'Blueshield QOL with other code cleanup' by Zergspower at commit 98f8ce4603](https://github.com/NovaSector/NovaSector/pull/2816)
[#2757: '[SEMI-MODULAR] Telecomms Specialist' by SciDragon at commit 7d647cc60e](https://github.com/NovaSector/NovaSector/pull/2757)
[#2852: 'Pipe Dreams: Disposals is actually usable as an escape again' by Ephemeralis at commit 341e39cc73](https://github.com/NovaSector/NovaSector/pull/2852)
[#2498: 'The End of the Galactic Materials Market: Economy shakeup' by Ephemeralis at commit b3299664a0](https://github.com/NovaSector/NovaSector/pull/2498)

Local commit: 2b150bba310f34604151e5a1d7f23d0e44b6f15a
TGS version: 6.5.0
DMAPI version: 5.9.0

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 0
Allow Latejoin Antagonists: 1

**Comment by TripleShades** [comment]
B.Exports is only called in three files, according to the repo, all relating to exports being sold. This is likely to deal with the GMM pr that is testmerged.

**Comment by Iajret** [comment]
No, `exports` is javascript related thing and has nothing to do with GMM. This error also appeared on fluffy frontier (and we do not have GMM changes test merged)

Probably https://github.com/NovaSector/NovaSector/pull/2682 caused this error because of missing `reqs` field or smth
