### ISSUE TITLE
Tape Recorder transcript TGUI bluescreen

### ISSUE THREAD

**Issue by GreytideSkye** [NovaSector/NovaSector#4443]
### Client Version:

515.1642

### Issue Summary:

A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 SyntaxError: Syntax error in regular expression
Please report this to https://github.com/markedjs/marked.
   at De (http://127.0.0.1:54805/asset.32d9c5dd8b5facc950f9baa2c9679ea7.js:410:121190)
   at Ze.emStrong (http://127.0.0.1:54805/asset.32d9c5dd8b5facc950f9baa2c9679ea7.js:416:59632)
   at lt (http://127.0.0.1:54805/asset.32d9c5dd8b5facc950f9baa2c9679ea7.js:416:75236)
   at Ze.inlineTokens (http://127.0.0.1:54805/asset.32d9c5dd8b5facc950f9baa2c9679ea7.js:416:76923)
   at Ze.lex (http://127.0.0.1:54805/asset.32d9c5dd8b5facc950f9baa2c9679ea7.js:416:71666)
   at it.lex (http://127.0.0.1:54805/asset.32d9c5dd8b5facc950f9baa2c9679ea7.js:416:77019)
   at Anonymous function (http://127.0.0.1:54805/asset.32d9c5dd8b5facc950f9baa2c9679ea7.js:416:86204)
   at at (http://127.0.0.1:54805/asset.32d9c5dd8b5facc950f9baa2c9679ea7.js:416:86383)
   at de.runMarkedDefault (http://127.0.0.1:54805/asset.32d9c5dd8b5facc950f9baa2c9679ea7.js:310:7694)
   at de.formatAndProcessRawText (http://127.0.0.1:54805/asset.32d9c5dd8b5facc950f9baa2c9679ea7.js:310:7900)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; wbx 1.0.0; wbxapp 1.0.0; Zoom 3.6.0)
State: {"ckey":"-my-ckey-","interface":"PaperSheet","window":{"key":"[0x203a6fe]-main","size":null,"fancy":1,"locked":1}}

Nanotrasen (c) 2525-540 

### Round ID:

11768

### Test Merge Information:

- [[TESTING ONLY] Debugging overlay cap being reached with taur parts](https://github.com/NovaSector/NovaSector/pull/2754)
- [Expands the item and ability selection of bitrunning disks (ft. Finally Being Able To Treat Your Teammates)](https://github.com/NovaSector/NovaSector/pull/4412)
- [Remove the Jaunter Creature from the gold slime pool](https://github.com/NovaSector/NovaSector/pull/4435)
- [Slime

### Reproduction Steps:

Print a Universal Recorder and a Tape for it from an autolathe. Talk into it for 10 minutes. Use it in hand, then the print report. Try to read the papers it prints out. TGUI bluescreen.

**Comment by Sadboysuss** [comment]
Reproducable by trying to use markdown on the paper, like _test_ and +test+
